# Generated by Django 2.1.2 on 2018-12-24 17:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artiste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_artiste', models.CharField(max_length=100, unique=True, verbose_name="nom d'artiste")),
                ('slug', models.SlugField(unique=True)),
                ('nom', models.CharField(blank=True, max_length=100)),
                ('prenom', models.CharField(blank=True, max_length=100, verbose_name='prénom')),
                ('ville', models.CharField(blank=True, max_length=100)),
                ('site_web', models.URLField(blank=True)),
                ('mail_contact', models.EmailField(blank=True, max_length=254, verbose_name='adresse mail de contact')),
                ('telephone_contact', models.CharField(blank=True, max_length=15, verbose_name='téléphone de contact')),
                ('cachet', models.DecimalField(blank=True, decimal_places=2, help_text="Il s'agit du prix moyen pour booker l'artiste.", max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('facebook_id', models.BigIntegerField(blank=True, null=True)),
                ('soundcloud_id', models.BigIntegerField(blank=True, null=True)),
                ('spotify_id', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
                ('artistes', models.ManyToManyField(blank=True, related_name='labels', to='music.Artiste')),
            ],
        ),
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='label',
            name='styles',
            field=models.ManyToManyField(blank=True, related_name='labels', to='music.Style'),
        ),
        migrations.AddField(
            model_name='artiste',
            name='pays',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='music.Pays'),
        ),
        migrations.AddField(
            model_name='artiste',
            name='styles',
            field=models.ManyToManyField(blank=True, related_name='artistes', to='music.Style'),
        ),
    ]
