# Generated by Django 2.2.2 on 2019-08-01 15:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0006_auto_20190731_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artiste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_artiste', models.CharField(max_length=100, unique=True, verbose_name="nom d'artiste")),
                ('slug', models.SlugField(unique=True)),
                ('nom', models.CharField(blank=True, max_length=100)),
                ('prenom', models.CharField(blank=True, max_length=100, verbose_name='prénom')),
                ('ville', models.CharField(blank=True, max_length=100)),
                ('site_web', models.URLField(blank=True)),
                ('mail_contact', models.EmailField(blank=True, max_length=254, verbose_name='adresse mail de contact')),
                ('telephone_contact', models.CharField(blank=True, max_length=15, verbose_name='téléphone de contact')),
                ('cachet', models.DecimalField(blank=True, decimal_places=2, help_text="Il s'agit du prix moyen pour booker l'artiste.", max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('facebook_id', models.BigIntegerField(blank=True, null=True)),
                ('soundcloud_id', models.BigIntegerField(blank=True, null=True)),
                ('spotify_id', models.BigIntegerField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='dernière modification')),
                ('createur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artistes_crees', to='base.Profil')),
            ],
            options={
                'ordering': ('nom_artiste',),
            },
        ),
        migrations.CreateModel(
            name='Musique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('album', models.CharField(blank=True, max_length=200)),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='dernière modification')),
                ('artiste', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='music.Artiste')),
                ('createur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='musiques_crees', to='base.Profil')),
            ],
            options={
                'ordering': ('artiste__nom_artiste', 'titre'),
            },
        ),
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Pays',
            },
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('description', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='dernière modification')),
                ('createur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists_crees', to='base.Profil')),
                ('styles', models.ManyToManyField(blank=True, related_name='playlists', to='music.Style')),
            ],
        ),
        migrations.CreateModel(
            name='MusiquePlaylist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name="date d'ajout de la musique dans la playlist")),
                ('musique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Musique')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Playlist')),
            ],
            options={
                'verbose_name': 'Musique de la playlist',
                'verbose_name_plural': 'Musiques de la playlist',
                'ordering': ('position',),
                'unique_together': {('playlist', 'musique'), ('playlist', 'position')},
            },
        ),
        migrations.AddField(
            model_name='musique',
            name='playlists',
            field=models.ManyToManyField(blank=True, related_name='musics', through='music.MusiquePlaylist', to='music.Playlist'),
        ),
        migrations.AddField(
            model_name='musique',
            name='styles',
            field=models.ManyToManyField(blank=True, related_name='musics', to='music.Style'),
        ),
        migrations.CreateModel(
            name='Lien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='lien vers la musique')),
                ('plateforme', models.CharField(blank=True, choices=[('SC', 'Soundcloud'), ('YT', 'YouTube'), ('SP', 'Spotify')], max_length=2)),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('createur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liens_crees', to='base.Profil')),
                ('musique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Musique')),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('artistes', models.ManyToManyField(blank=True, related_name='labels', to='music.Artiste')),
                ('styles', models.ManyToManyField(blank=True, related_name='labels', to='music.Style')),
            ],
            options={
                'ordering': ('nom',),
            },
        ),
        migrations.AddField(
            model_name='artiste',
            name='pays',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='music.Pays'),
        ),
        migrations.AddField(
            model_name='artiste',
            name='styles',
            field=models.ManyToManyField(blank=True, related_name='artistes', to='music.Style'),
        ),
        migrations.AlterUniqueTogether(
            name='musique',
            unique_together={('artiste', 'titre')},
        ),
    ]
