# Generated by Django 2.1.10 on 2019-08-02 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lien',
            name='musique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liens', to='music.Musique'),
        ),
        migrations.AlterField(
            model_name='musique',
            name='artiste',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='musiques', to='music.Artiste'),
        ),
        migrations.AlterField(
            model_name='musique',
            name='playlists',
            field=models.ManyToManyField(blank=True, related_name='musiques', through='music.MusiquePlaylist', to='music.Playlist'),
        ),
        migrations.AlterField(
            model_name='musique',
            name='styles',
            field=models.ManyToManyField(blank=True, related_name='musiques', to='music.Style'),
        ),
    ]
