# Generated by Django 2.1.2 on 2018-12-24 17:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artiste',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date de création'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artiste',
            name='date_modification',
            field=models.DateTimeField(auto_now=True, verbose_name='dernière modification'),
        ),
    ]
