# Generated by Django 2.1.2 on 2018-12-24 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0002_auto_20181224_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='artiste',
            name='createur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artistes_crees', to=settings.AUTH_USER_MODEL),
        ),
    ]
