# Generated by Django 2.2.2 on 2019-08-13 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20190802_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='styles',
        ),
    ]
