# Generated by Django 2.2.2 on 2019-07-31 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0003_artiste_createur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Musique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('album', models.CharField(blank=True, max_length=200)),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='dernière modification')),
            ],
            options={
                'ordering': ('artiste__nom_artiste', 'titre'),
            },
        ),
        migrations.AlterModelOptions(
            name='artiste',
            options={'ordering': ('nom_artiste',)},
        ),
        migrations.AlterModelOptions(
            name='label',
            options={'ordering': ('nom',)},
        ),
        migrations.AlterModelOptions(
            name='pays',
            options={'verbose_name_plural': 'Pays'},
        ),
        migrations.AddField(
            model_name='label',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='label',
            name='slug',
            field=models.SlugField(default='', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artiste',
            name='pays',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='music.Pays'),
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('description', models.TextField(blank=True)),
                ('createur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists_crees', to=settings.AUTH_USER_MODEL)),
                ('styles', models.ManyToManyField(blank=True, related_name='playlists', to='music.Style')),
            ],
        ),
        migrations.CreateModel(
            name='MusiquePlaylist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name="date d'ajout de la musique dans la playlist")),
                ('musique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Musique')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Playlist')),
            ],
            options={
                'verbose_name': 'Musique de la playlist',
                'verbose_name_plural': 'Musiques de la playlist',
                'unique_together': {('playlist', 'musique')},
            },
        ),
        migrations.AddField(
            model_name='musique',
            name='artiste',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='music.Artiste'),
        ),
        migrations.AddField(
            model_name='musique',
            name='createur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='musiques_crees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='musique',
            name='playlists',
            field=models.ManyToManyField(blank=True, related_name='musics', through='music.MusiquePlaylist', to='music.Playlist'),
        ),
        migrations.AddField(
            model_name='musique',
            name='styles',
            field=models.ManyToManyField(blank=True, related_name='musics', to='music.Style'),
        ),
        migrations.CreateModel(
            name='Lien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='lien vers la musique')),
                ('plateforme', models.CharField(blank=True, choices=[('SC', 'Soundcloud'), ('YT', 'YouTube'), ('SP', 'Spotify')], max_length=2)),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('createur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liens_crees', to=settings.AUTH_USER_MODEL)),
                ('musique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Musique')),
            ],
        ),
    ]
