# Generated by Django 2.2.2 on 2019-08-13 09:52

import adminsortable.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_remove_playlist_styles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musiqueplaylist',
            name='playlist',
            field=adminsortable.fields.SortableForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Playlist'),
        ),
        migrations.AlterField(
            model_name='musiqueplaylist',
            name='position',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AlterUniqueTogether(
            name='musiqueplaylist',
            unique_together={('playlist', 'musique')},
        ),
    ]
