# Generated by Django 2.2.2 on 2019-08-01 15:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20190731_1740'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='musiqueplaylist',
            options={'ordering': ('position',), 'verbose_name': 'Musique de la playlist', 'verbose_name_plural': 'Musiques de la playlist'},
        ),
        migrations.AddField(
            model_name='musiqueplaylist',
            name='position',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playlist',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date de création'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playlist',
            name='date_modification',
            field=models.DateTimeField(auto_now=True, verbose_name='dernière modification'),
        ),
        migrations.AlterUniqueTogether(
            name='musique',
            unique_together={('artiste', 'titre')},
        ),
        migrations.AlterUniqueTogether(
            name='musiqueplaylist',
            unique_together={('playlist', 'musique'), ('playlist', 'position')},
        ),
    ]
