# Generated by Django 2.2.2 on 2019-08-01 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_auto_20190801_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artiste',
            name='createur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artistes_crees', to='base.Profil'),
        ),
        migrations.AlterField(
            model_name='lien',
            name='createur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liens_crees', to='base.Profil'),
        ),
        migrations.AlterField(
            model_name='musique',
            name='createur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='musiques_crees', to='base.Profil'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='createur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists_crees', to='base.Profil'),
        ),
    ]
