# Generated by Django 2.1.11 on 2019-08-18 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_auto_20190816_0800'),
    ]

    operations = [
        migrations.AddField(
            model_name='musique',
            name='featuring',
            field=models.ManyToManyField(blank=True, help_text='Les artistes qui ont participé à la musique.', related_name='musiques_featuring', to='music.Artiste'),
        ),
        migrations.AddField(
            model_name='musique',
            name='remixed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='remixes', to='music.Artiste', verbose_name='remixé par'),
        ),
        migrations.AlterField(
            model_name='musique',
            name='artiste',
            field=models.ForeignKey(help_text='Artiste principal de la musique.', on_delete=django.db.models.deletion.PROTECT, related_name='musiques', to='music.Artiste'),
        ),
    ]
