# Generated by Django 2.1.11 on 2019-08-18 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20190731_1549'),
        ('music', '0006_auto_20190818_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='dernière modification')),
                ('artistes', models.ManyToManyField(related_name='artistes', to='music.Artiste')),
                ('createur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groupes_crees', to='base.Profil')),
            ],
            options={
                'ordering': ('nom',),
            },
        ),
    ]
