# Generated by Django 2.1.11 on 2019-10-28 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_auto_20190818_1504'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playlist',
            options={'ordering': ('nom',)},
        ),
    ]
