# Generated by Django 2.1.11 on 2019-08-18 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_groupe'),
    ]

    operations = [
        migrations.AddField(
            model_name='musique',
            name='groupe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='musiques', to='music.Groupe'),
        ),
        migrations.AlterField(
            model_name='musique',
            name='artiste',
            field=models.ForeignKey(blank=True, help_text='Artiste principal de la musique.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='musiques', to='music.Artiste'),
        ),
    ]
