# Generated by Django 2.2.12 on 2020-06-27 09:07

from django.db import migrations, models
from slugify import slugify


def create_slug(apps, schema_editor):
    Style = apps.get_model("music", "Style")
    db_alias = schema_editor.connection.alias
    for style in Style.objects.using(db_alias).all():
        style.slug = slugify(style.nom)
        style.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_lien_date_validation'),
    ]

    operations = [
        migrations.AddField(
            model_name='style',
            name='slug',
            field=models.SlugField(unique=True, null=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AddField(
            model_name='style',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='style',
            name='lien_wiki',
            field=models.URLField(blank=True),
        ),
        migrations.RunPython(create_slug, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='style',
            name='slug',
            field=models.SlugField(unique=True),
        )
    ]
