# Generated by Django 2.2.12 on 2020-06-27 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_auto_20200627_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='musique',
            name='label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='musiques', to='music.Label'),
        ),
    ]
