# Generated by Django 2.2.12 on 2020-06-27 14:09

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0008_projet_position'),
        ('music', '0010_musique_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalMusique',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('titre', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('album', models.CharField(blank=True, max_length=200)),
                ('date_creation', models.DateTimeField(blank=True, editable=False, verbose_name='date de création')),
                ('date_modification', models.DateTimeField(blank=True, editable=False, verbose_name='dernière modification')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('artiste', models.ForeignKey(blank=True, db_constraint=False, help_text='Artiste principal de la musique.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='music.Artiste')),
                ('createur', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.Profil')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('label', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='music.Label')),
                ('remixed_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='music.Artiste', verbose_name='remixé par')),
            ],
            options={
                'verbose_name': 'historical musique',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalArtiste',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nom_artiste', models.CharField(db_index=True, max_length=100, verbose_name="nom d'artiste")),
                ('slug', models.SlugField()),
                ('prenom', models.CharField(blank=True, max_length=100, verbose_name='prénom')),
                ('nom', models.CharField(blank=True, max_length=100)),
                ('ville', models.CharField(blank=True, max_length=100)),
                ('site_web', models.URLField(blank=True)),
                ('mail_contact', models.EmailField(blank=True, max_length=254, verbose_name='adresse mail de contact')),
                ('telephone_contact', models.CharField(blank=True, max_length=15, verbose_name='téléphone de contact')),
                ('cachet', models.DecimalField(blank=True, decimal_places=2, help_text="Il s'agit du prix moyen pour booker l'artiste.", max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('facebook_id', models.BigIntegerField(blank=True, null=True)),
                ('soundcloud_id', models.BigIntegerField(blank=True, null=True)),
                ('spotify_id', models.BigIntegerField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(blank=True, editable=False, verbose_name='date de création')),
                ('date_modification', models.DateTimeField(blank=True, editable=False, verbose_name='dernière modification')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('createur', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.Profil')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('pays', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='music.Pays')),
            ],
            options={
                'verbose_name': 'historical artiste',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
