# Generated by Django 2.2.13 on 2020-09-17 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0011_historicalartiste_historicalmusique'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='musique',
            unique_together={('artiste', 'titre', 'remixed_by')},
        ),
    ]
