# Generated by Django 2.2.18 on 2021-03-29 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0012_auto_20200917_1946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lien',
            old_name='plateforme',
            new_name='old_plateforme',
        ),
    ]
