# Generated by Django 2.2.18 on 2021-03-29 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0013_auto_20210329_2355'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plateforme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.RunSQL(
            sql='INSERT INTO music_plateforme (id, nom, slug) VALUES '
                '(1, "Youtube", "youtube"),'
                '(2, "Soundcloud", "soundcloud"),'
                '(3, "Spotify", "spotify");',
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.AddField(
            model_name='lien',
            name='plateforme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='music.Plateforme'),
        ),
        migrations.RunSQL(
            sql='UPDATE music_lien SET plateforme_id=CASE '
                'WHEN old_plateforme="YT" THEN 1 '
                'WHEN old_plateforme="SC" THEN 2 '
                'WHEN old_plateforme="SP" THEN 3 '
                'ELSE null END;',
            reverse_sql='UPDATE music_lien SET old_plateforme=CASE '
                        'WHEN plateforme_id=1 THEN "YT" '
                        'WHEN plateforme_id=2 THEN "SC" '
                        'WHEN plateforme_id=3 THEN "SP" '
                        'ELSE "" END;'
        ),
        migrations.RemoveField(
            model_name='lien',
            name='old_plateforme',
        ),
    ]
