# Generated by Django 2.2.18 on 2021-04-02 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0015_lienplaylist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lien',
            name='click_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Click count'),
        ),
        migrations.AlterField(
            model_name='lien',
            name='createur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liens_crees', to='base.Profil', verbose_name='Creator'),
        ),
        migrations.AlterField(
            model_name='lien',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creation date'),
        ),
        migrations.AlterField(
            model_name='lien',
            name='date_validation',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Validation date'),
        ),
        migrations.AlterField(
            model_name='lien',
            name='musique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liens', to='music.Musique', verbose_name='Music'),
        ),
        migrations.AlterField(
            model_name='lien',
            name='plateforme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='music.Plateforme', verbose_name='Platform'),
        ),
        migrations.AlterField(
            model_name='lien',
            name='url',
            field=models.URLField(verbose_name='Link to the music'),
        ),
    ]
