# Generated by Django 5.2.12 on 2026-05-02 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0016_auto_20210403_0106'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalartiste',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical artiste', 'verbose_name_plural': 'historical artistes'},
        ),
        migrations.AlterModelOptions(
            name='historicalmusique',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical musique', 'verbose_name_plural': 'historical musiques'},
        ),
        migrations.AlterField(
            model_name='historicalartiste',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalmusique',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
