# Generated by Django 2.2.9 on 2020-02-04 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_projet_position'),
        ('my_spot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpotGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('slug', models.SlugField(null=True, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='spot',
            name='groupes',
            field=models.ManyToManyField(blank=True, related_name='spots', to='my_spot.SpotGroup', verbose_name='partagé aux groupes'),
        ),
        migrations.AlterField(
            model_name='spot',
            name='visibilite',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Public'), (2, 'Partagé'), (3, 'Caché')], default=3, help_text='Visbilité du spot : Public = visible par tous ; Partagé = visible par les membre du groupe ; Caché = seul le possésseur peut le voir.', verbose_name='visibilité'),
        ),
        migrations.CreateModel(
            name='SpotGroupProfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name="date d'ajout au groupe")),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Profil')),
                ('spot_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_spot.SpotGroup')),
            ],
        ),
        migrations.AddField(
            model_name='spotgroup',
            name='profils',
            field=models.ManyToManyField(blank=True, related_name='spot_groups', through='my_spot.SpotGroupProfil', to='base.Profil'),
        ),
    ]
