# Generated by Django 2.2.9 on 2020-02-04 22:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('my_spot', '0002_auto_20200204_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotgroup',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date de création'),
            preserve_default=False,
        ),
    ]
