# Generated by Django 2.2.12 on 2020-05-15 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_spot', '0004_auto_20200318_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotphoto',
            name='photo',
            field=models.TextField(default='placeholder.jpg', verbose_name='url photo'),
        ),
    ]
