# Generated by Django 5.2.12 on 2026-05-02 21:43

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_spot', '0007_auto_20200610_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spottag',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='couleur'),
        ),
    ]
