# Generated by Django 2.2.13 on 2020-06-30 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0008_projet_position'),
        ('kendama', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalTrickPlayer',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('frequency', models.PositiveSmallIntegerField(choices=[(1, 'Impossible'), (2, 'Seulement une fois'), (3, 'Rarement'), (4, 'Parfois'), (5, 'Généralement'), (6, 'Tout le temps')], default=1, verbose_name='fréquence de réussite')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='date création')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('player', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.Profil', verbose_name='joueur')),
                ('trick', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='kendama.KendamaTrick')),
            ],
            options={
                'verbose_name': 'historical trick de joueur',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalComboPlayer',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('frequency', models.PositiveSmallIntegerField(choices=[(1, 'Impossible'), (2, 'Seulement une fois'), (3, 'Rarement'), (4, 'Parfois'), (5, 'Généralement'), (6, 'Tout le temps')], default=1, verbose_name='fréquence de réussite')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='date création')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('combo', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='kendama.Combo')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('player', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.Profil', verbose_name='joueur')),
            ],
            options={
                'verbose_name': 'historical combo de joueur',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
