# Generated by Django 2.2.13 on 2020-07-01 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_projet_position'),
        ('kendama', '0003_auto_20200701_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='combo',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='combos', through='kendama.ComboPlayer', to='base.Profil', verbose_name='joueurs'),
        ),
        migrations.AddField(
            model_name='kendamatrick',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='tricks', through='kendama.TrickPlayer', to='base.Profil', verbose_name='joueurs'),
        ),
    ]
