# Generated by Django 2.2.13 on 2020-07-06 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kendama', '0006_auto_20200705_1929'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='combo',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='kendamatrick',
            options={'ordering': ('name',), 'verbose_name': 'trick de Kendama', 'verbose_name_plural': 'tricks de Kendama'},
        ),
    ]
