# Generated by Django 2.2.13 on 2020-07-19 11:06

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_projet_position'),
        ('kendama', '0007_auto_20200706_2305'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ladder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nom')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date mise à jour')),
                ('difficulty', models.PositiveSmallIntegerField(choices=[(1, 'Débutant'), (2, 'Intermédiaire'), (3, 'Avancé')], verbose_name='difficulté')),
                ('tutorial_video_link', models.URLField(blank=True, verbose_name='lien vidéo tutoriel')),
            ],
            options={
                'verbose_name': 'ladder',
                'verbose_name_plural': 'ladders',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='LadderCombo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='ordre')),
                ('combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ladder_combos', to='kendama.Combo')),
                ('ladder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ladder_combos', to='kendama.Ladder')),
            ],
            options={
                'ordering': ('ladder', 'order'),
                'unique_together': {('ladder', 'combo', 'order')},
            },
        ),
        migrations.AddField(
            model_name='ladder',
            name='combos',
            field=models.ManyToManyField(related_name='ladders', through='kendama.LadderCombo', to='kendama.Combo'),
        ),
        migrations.AddField(
            model_name='ladder',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.Profil', verbose_name='créateur'),
        ),
    ]
