# Generated by Django 2.2.13 on 2020-07-23 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kendama', '0008_auto_20200719_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comboplayer',
            name='frequency',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Jamais'), (2, 'Seulement une fois'), (3, 'Rarement (environ 10%)'), (4, 'Parfois (environ 33%)'), (5, 'Généralement (environ 66%)'), (6, 'Presque toujours (environ 99%)')], default=1, verbose_name='fréquence de réussite'),
        ),
        migrations.AlterField(
            model_name='historicalcomboplayer',
            name='frequency',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Jamais'), (2, 'Seulement une fois'), (3, 'Rarement (environ 10%)'), (4, 'Parfois (environ 33%)'), (5, 'Généralement (environ 66%)'), (6, 'Presque toujours (environ 99%)')], default=1, verbose_name='fréquence de réussite'),
        ),
        migrations.AlterField(
            model_name='historicaltrickplayer',
            name='frequency',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Jamais'), (2, 'Seulement une fois'), (3, 'Rarement (environ 10%)'), (4, 'Parfois (environ 33%)'), (5, 'Généralement (environ 66%)'), (6, 'Presque toujours (environ 99%)')], default=1, verbose_name='fréquence de réussite'),
        ),
        migrations.AlterField(
            model_name='trickplayer',
            name='frequency',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Jamais'), (2, 'Seulement une fois'), (3, 'Rarement (environ 10%)'), (4, 'Parfois (environ 33%)'), (5, 'Généralement (environ 66%)'), (6, 'Presque toujours (environ 99%)')], default=1, verbose_name='fréquence de réussite'),
        ),
    ]
