# Generated by Django 5.2.12 on 2026-05-02 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kendama', '0011_ladder_private'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalcomboplayer',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical combo de joueur', 'verbose_name_plural': 'historical combos de joueur'},
        ),
        migrations.AlterModelOptions(
            name='historicaltrickplayer',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical trick de joueur', 'verbose_name_plural': 'historical tricks de joueur'},
        ),
        migrations.AlterField(
            model_name='historicalcomboplayer',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicaltrickplayer',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
