# Generated by Django 2.0.1 on 2018-01-08 22:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    operations = [
        migrations.CreateModel(
            name='Avis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avis', models.TextField(blank=True, help_text='Ton avis en quelques mots sur le plat')),
                ('note', models.PositiveIntegerField(default=5, help_text='Une note entre 0 et 10')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='avis/')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name="date d'ajout")),
            ],
            options={
                'verbose_name_plural': 'avis',
                'verbose_name': 'Avis',
            },
        ),
        migrations.CreateModel(
            name='Plat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, help_text='Une description du plat')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=4)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='plats/')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name="date d'ajout")),
            ],
            options={
                'verbose_name': 'Plat',
            },
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil',
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('informations', models.TextField(blank=True, help_text='Informations utiles et relatives au restaurant')),
                ('adresse', models.CharField(blank=True, max_length=200)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name="date d'ajout")),
            ],
            options={
                'verbose_name': 'Restaurant',
            },
        ),
        migrations.AddField(
            model_name='plat',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='avis.Restaurant'),
        ),
        migrations.AddField(
            model_name='avis',
            name='auteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='avis.Profil'),
        ),
        migrations.AddField(
            model_name='avis',
            name='plat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='avis.Plat'),
        ),
    ]
