# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-28 16:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Avis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avis', models.TextField(blank=True)),
                ('note', models.PositiveIntegerField(default=5)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='avis/')),
            ],
        ),
        migrations.CreateModel(
            name='Plat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=4)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='plats/')),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('adresse', models.CharField(blank=True, max_length=200)),
                ('telephone', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('plat', models.ManyToManyField(to='avis.Plat')),
            ],
        ),
        migrations.AddField(
            model_name='plat',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='avis.Restaurant'),
        ),
        migrations.AddField(
            model_name='avis',
            name='auteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='avis.Profil'),
        ),
        migrations.AddField(
            model_name='avis',
            name='plat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='avis.Plat'),
        ),
    ]
