# Generated by Django 2.1b1 on 2018-08-06 20:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import geoposition.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avis', models.TextField(blank=True, help_text='Ton avis en quelques mots sur le plat')),
                ('note', models.PositiveIntegerField(default=5, help_text='Une note entre 0 et 10', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('photo', models.ImageField(blank=True, null=True, upload_to='media/avis/')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name="date d'ajout")),
                ('date_edition', models.DateTimeField(auto_now=True, verbose_name='date de dernière modification')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.Profil')),
            ],
            options={
                'verbose_name_plural': 'avis',
            },
        ),
        migrations.CreateModel(
            name='Plat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, help_text='Une description du plat')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=4)),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name="date d'ajout")),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('informations', models.TextField(blank=True, help_text='Informations utiles et relatives au restaurant')),
                ('lien', models.URLField(blank=True, help_text='Le lien vers le site internet', max_length=255)),
                ('telephone', models.CharField(blank=True, help_text='Indicatif facultatif et sans espaces.', max_length=20, validators=[django.core.validators.RegexValidator('^(0|\\+33|0033)[1-9][0-9]{8}$', "Ce numéro n'est pas valide.")])),
                ('adresse', geoposition.fields.GeopositionField(blank=True, max_length=42)),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name="date d'ajout")),
            ],
        ),
        migrations.AddField(
            model_name='plat',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='avis.Restaurant'),
        ),
        migrations.AddField(
            model_name='avis',
            name='plat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='avis.Plat'),
        ),
    ]
