# Generated by Django 2.0.1 on 2018-01-08 22:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avis',
            name='note',
            field=models.PositiveIntegerField(default=5, help_text='Une note entre 0 et 10', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
