# Generated by Django 2.1b1 on 2018-08-06 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
