# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-28 16:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('avis', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avis',
            options={'verbose_name_plural': 'avis'},
        ),
        migrations.AddField(
            model_name='avis',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name="date d'ajout"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plat',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name="date d'ajout"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profil',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date de création'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name="date d'ajout"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='informations',
            field=models.TextField(blank=True, help_text='Informations utiles et relatives au restaurant'),
        ),
        migrations.AlterField(
            model_name='avis',
            name='avis',
            field=models.TextField(blank=True, help_text='Ton avis en quelques mots sur le plat'),
        ),
        migrations.AlterField(
            model_name='avis',
            name='note',
            field=models.PositiveIntegerField(default=5, help_text='Une note entre 0 et 10'),
        ),
        migrations.AlterField(
            model_name='plat',
            name='description',
            field=models.TextField(blank=True, help_text='Une description du plat'),
        ),
    ]
