# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-28 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avis', '0002_auto_20171028_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='plat',
        ),
        migrations.AddField(
            model_name='plat',
            name='tags',
            field=models.ManyToManyField(to='avis.Tag'),
        ),
    ]
