# Generated by Django 2.1.1 on 2018-09-18 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avis', '0002_restaurant_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avis',
            options={'ordering': ('-date_edition',), 'verbose_name_plural': 'avis'},
        ),
    ]
