# Generated by Django 2.0.1 on 2018-01-08 23:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avis', '0002_auto_20180108_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avis',
            name='note',
            field=models.PositiveIntegerField(default=5, help_text='Une note entre 0 et 10', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='plat',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/plats/'),
        ),
        migrations.AlterField(
            model_name='profil',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='media/avatars/'),
        ),
    ]
