# Generated by Django 2.1.2 on 2018-10-24 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avis', '0003_auto_20180919_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avis',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='avis/'),
        ),
    ]
