# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-28 17:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avis', '0003_auto_20171028_1834'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avis',
            old_name='date_add',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='plat',
            old_name='date_add',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='profil',
            old_name='date_add',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='date_add',
            new_name='date',
        ),
    ]
