# Generated by Django 2.0.4 on 2018-05-16 21:31

from django.db import migrations, models
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('avis', '0003_auto_20180108_2312'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avis',
            options={'verbose_name_plural': 'avis'},
        ),
        migrations.AlterModelOptions(
            name='plat',
            options={},
        ),
        migrations.AlterModelOptions(
            name='profil',
            options={},
        ),
        migrations.AlterModelOptions(
            name='restaurant',
            options={},
        ),
        migrations.RenameField(
            model_name='avis',
            old_name='date',
            new_name='date_creation',
        ),
        migrations.RenameField(
            model_name='plat',
            old_name='date',
            new_name='date_creation',
        ),
        migrations.RenameField(
            model_name='profil',
            old_name='date',
            new_name='date_creation',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='date',
            new_name='date_creation',
        ),
        migrations.AddField(
            model_name='avis',
            name='date_edition',
            field=models.DateTimeField(auto_now=True, verbose_name='date de dernière modification'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='lien',
            field=models.URLField(blank=True, help_text='Le lien vers le site internet', max_length=255),
        ),
        migrations.AlterField(
            model_name='avis',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/avis/'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='adresse',
            field=geoposition.fields.GeopositionField(blank=True, max_length=42, null=True),
        ),
    ]
