# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-28 18:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avis', '0004_auto_20171028_1917'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avis',
            options={'verbose_name': 'Avis', 'verbose_name_plural': 'avis'},
        ),
        migrations.AlterModelOptions(
            name='plat',
            options={'verbose_name': 'Plat'},
        ),
        migrations.AlterModelOptions(
            name='profil',
            options={'verbose_name': 'Profil'},
        ),
        migrations.AlterModelOptions(
            name='restaurant',
            options={'verbose_name': 'Restaurant'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Tag'},
        ),
    ]
