# Generated by Django 2.1a1 on 2018-06-18 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avis', '0005_auto_20180517_0022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plat',
            name='photo',
        ),
    ]
