# Generated by Django 2.1.2 on 2018-11-28 10:28

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('avis', '0005_auto_20181024_2347'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Restaurant',
            new_name='Structure',
        ),
    ]
