# Generated by Django 2.1b1 on 2018-07-18 14:21

from django.db import migrations
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('avis', '0006_remove_plat_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='adresse',
            field=geoposition.fields.GeopositionField(blank=True, max_length=42),
        ),
    ]
