# Generated by Django 2.1b1 on 2018-07-24 20:05

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('avis', '0007_auto_20180718_1621'),
    ]

    database_operations = [migrations.AlterModelTable('Profil', 'base_profil')]

    state_operations = [migrations.DeleteModel('Profil')]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations
        )
    ]
