# Generated by Django 2.1.2 on 2018-11-28 14:27

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('avis', '0007_auto_20181128_1132'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Plat',
            new_name='Produit',
        ),
        migrations.AlterModelOptions(
            name='typestructure',
            options={'verbose_name': 'type de structure', 'verbose_name_plural': 'types de structure'},
        ),
    ]
