# Generated by Django 2.1.2 on 2018-11-28 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avis', '0008_auto_20181128_1527'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avis',
            old_name='plat',
            new_name='produit',
        ),
        migrations.AlterField(
            model_name='avis',
            name='avis',
            field=models.TextField(blank=True, help_text='Ton avis en quelques mots sur le produit'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='description',
            field=models.TextField(blank=True, help_text='Une description du produit'),
        ),
    ]
