# Generated by Django 2.1.2 on 2018-11-28 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avis', '0009_auto_20181128_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieProduit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('produits', models.ManyToManyField(to='avis.Produit')),
                ('types_structure', models.ManyToManyField(help_text='Selectionnez les types de structure possédant cette catégorie', to='avis.TypeStructure')),
            ],
        ),
    ]
