# Generated by Django 2.1.2 on 2018-11-28 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avis', '0010_categorieproduit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorieproduit',
            options={'verbose_name': 'catégorie de produit', 'verbose_name_plural': 'catégories de produit'},
        ),
        migrations.RemoveField(
            model_name='categorieproduit',
            name='produits',
        ),
        migrations.RemoveField(
            model_name='categorieproduit',
            name='types_structure',
        ),
        migrations.AddField(
            model_name='produit',
            name='categories',
            field=models.ManyToManyField(help_text='Sélectionnez les catégories de ce produit.', to='avis.CategorieProduit'),
        ),
        migrations.AddField(
            model_name='typestructure',
            name='categories',
            field=models.ManyToManyField(help_text='Selectionnez les catégories de produit possibles pour ce type de structure.', to='avis.CategorieProduit'),
        ),
        migrations.AlterField(
            model_name='avis',
            name='avis',
            field=models.TextField(blank=True, help_text='Ton avis en quelques mots sur le produit.'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='description',
            field=models.TextField(blank=True, help_text='Une description du produit.'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='informations',
            field=models.TextField(blank=True, help_text='Informations utiles et relatives à la structure.'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='lien',
            field=models.URLField(blank=True, help_text='Le lien vers le site internet.', max_length=255),
        ),
    ]
