# Generated by Django 2.1.2 on 2018-11-28 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avis', '0011_auto_20181128_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorieproduit',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Sélectionnez la ou les catégories de ce produit.', to='avis.CategorieProduit'),
        ),
        migrations.AlterField(
            model_name='typestructure',
            name='categories',
            field=models.ManyToManyField(help_text='Selectionnez la ou les catégories de produit possibles pour ce type de structure.', to='avis.CategorieProduit'),
        ),
    ]
