# Generated by Django 2.1.2 on 2018-12-24 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avis', '0013_avis_prive'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorieproduit',
            options={'ordering': ('nom',), 'verbose_name': 'catégorie de produit', 'verbose_name_plural': 'catégories de produit'},
        ),
    ]
