# Generated by Django 5.2.12 on 2026-05-29 15:56

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avis', '0016_auto_20200516_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avis',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=base.models.photo_upload_to, verbose_name='photo'),
        ),
    ]
