# Generated by Django 6.1 on 2026-08-23 00:58

import autoslug.fields
import colorfield.fields
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import fontawesome_6.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0008_projet_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('unite', models.CharField(blank=True, choices=[('unite', 'unité'), ('kg', 'kg'), ('g', 'g'), ('l', 'L'), ('ml', 'mL'), ('paquet', 'paquet'), ('boite', 'boîte'), ('sachet', 'sachet'), ('bouteille', 'bouteille')], default='', help_text="Laissé vide par l'import (§9) tant que l'unité n'est pas confirmée.", max_length=10)),
                ('conditionnement', models.DecimalField(decimal_places=3, default=1, help_text="Unités de conso par unité d'achat (ex. 1,5 pour une bouteille de 1,5 L).", max_digits=9, validators=[django.core.validators.MinValueValidator(0)])),
                ('stock_cible', models.DecimalField(decimal_places=3, default=0, help_text='Niveau normal souhaité à la maison (le « want » du POC).', max_digits=9, validators=[django.core.validators.MinValueValidator(0)])),
                ('stock_reference', models.DecimalField(decimal_places=3, default=0, help_text='Stock figé au dernier achat/recalage (le « have » du POC).', max_digits=9, validators=[django.core.validators.MinValueValidator(0)])),
                ('stock_maj_le', models.DateTimeField(blank=True, null=True)),
                ('conso_par_jour_estimee', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('conso_amorce', models.DecimalField(blank=True, decimal_places=3, help_text='Graine de démarrage, lue uniquement tant que conso_par_jour_estimee est vide.', max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('suivi_auto', models.BooleanField(default=True, verbose_name='suivi automatique')),
                ('actif', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('supprime_le', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('nom',),
            },
        ),
        migrations.CreateModel(
            name='Etiquette',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('couleur', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'étiquette',
                'ordering': ('nom',),
            },
        ),
        migrations.CreateModel(
            name='ArticleMagasin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(help_text="Tel que le ticket ou le drive l'écrit.", max_length=200)),
                ('marque', models.CharField(blank=True, max_length=100)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles_magasin', to='courses.article')),
            ],
            options={
                'verbose_name': 'article en magasin',
                'verbose_name_plural': 'articles en magasin',
                'ordering': ('libelle',),
            },
        ),
        migrations.AddField(
            model_name='article',
            name='etiquettes',
            field=models.ManyToManyField(blank=True, related_name='articles', to='courses.etiquette'),
        ),
        migrations.CreateModel(
            name='Foyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='nom', unique=True)),
                ('archive', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('membres', models.ManyToManyField(related_name='foyers', to='base.profil')),
            ],
            options={
                'ordering': ('nom',),
            },
        ),
        migrations.AddField(
            model_name='etiquette',
            name='foyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etiquettes', to='courses.foyer'),
        ),
        migrations.AddField(
            model_name='article',
            name='foyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='courses.foyer'),
        ),
        migrations.CreateModel(
            name='Ligne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=3, default=1, max_digits=9, validators=[django.core.validators.MinValueValidator(0)])),
                ('cochee_le', models.DateTimeField(blank=True, null=True)),
                ('indisponible_le', models.DateTimeField(blank=True, null=True)),
                ('prix_unitaire', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('origine', models.CharField(choices=[('manuel', 'Manuel'), ('seuil', 'Seuil'), ('suggestion', 'Suggestion'), ('import', 'Import')], default='manuel', max_length=10)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('supprime_le', models.DateTimeField(blank=True, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='courses.article')),
                ('article_magasin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes', to='courses.articlemagasin')),
                ('cochee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_cochees', to='base.profil')),
            ],
        ),
        migrations.CreateModel(
            name='Magasin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('enseigne', models.CharField(blank=True, max_length=100)),
                ('actif', models.BooleanField(default=True)),
                ('foyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='magasins', to='courses.foyer')),
            ],
            options={
                'ordering': ('nom',),
            },
        ),
        migrations.AddField(
            model_name='articlemagasin',
            name='magasin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles_magasin', to='courses.magasin'),
        ),
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('achat', 'Achat'), ('recalage', 'Recalage'), ('perte', 'Perte')], max_length=10)),
                ('quantite', models.DecimalField(decimal_places=3, help_text='Toujours positive — le type porte le signe : achat = ajoutée au stock, perte = retirée du stock, recalage = NOUVELLE VALEUR ABSOLUE du stock (ni un ajout ni un retrait).', max_digits=9, validators=[django.core.validators.MinValueValidator(0)])),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('commentaire', models.CharField(blank=True, max_length=255)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('supprime_le', models.DateTimeField(blank=True, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='courses.article')),
                ('ligne', models.ForeignKey(blank=True, help_text="La Ligne à l'origine de ce mouvement — sans elle, « Corriger » ne peut rien défaire.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements', to='courses.ligne')),
                ('profil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_stock', to='base.profil')),
            ],
            options={
                'verbose_name': 'mouvement de stock',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='Rayon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('ordre', models.PositiveIntegerField(db_index=True, default=0)),
                ('couleur', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None)),
                ('icone', fontawesome_6.fields.IconField(blank=True, max_length=60, verbose_name='icône')),
                ('foyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rayons', to='courses.foyer')),
            ],
            options={
                'ordering': ('ordre',),
                'unique_together': {('foyer', 'nom')},
            },
        ),
        migrations.AddField(
            model_name='article',
            name='rayon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='courses.rayon'),
        ),
        migrations.CreateModel(
            name='Sortie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=100)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('cloture_le', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(choices=[('manuel', 'Manuel'), ('ticket', 'Ticket de caisse'), ('drive', 'Drive')], default='manuel', max_length=10)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('supprime_le', models.DateTimeField(blank=True, null=True)),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sorties_creees', to='base.profil')),
                ('foyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sorties', to='courses.foyer')),
                ('magasin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sorties', to='courses.magasin')),
            ],
            options={
                'ordering': ('-cree_le',),
            },
        ),
        migrations.AddField(
            model_name='ligne',
            name='sortie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='courses.sortie'),
        ),
        migrations.CreateModel(
            name='DemandePonctuelle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=3, default=1, max_digits=9, validators=[django.core.validators.MinValueValidator(0)])),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('supprime_le', models.DateTimeField(blank=True, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_ponctuelles', to='courses.article')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_ponctuelles', to='base.profil')),
                ('satisfaite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_satisfaites', to='courses.ligne')),
                ('sortie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_ponctuelles', to='courses.sortie')),
            ],
            options={
                'verbose_name': 'demande ponctuelle',
                'ordering': ('-date',),
            },
        ),
        migrations.AlterUniqueTogether(
            name='etiquette',
            unique_together={('foyer', 'nom')},
        ),
        migrations.AlterUniqueTogether(
            name='articlemagasin',
            unique_together={('magasin', 'libelle')},
        ),
        migrations.AddConstraint(
            model_name='ligne',
            constraint=models.UniqueConstraint(fields=('sortie', 'article'), name='un_article_une_fois_par_sortie'),
        ),
    ]
