# Generated by Django 2.1b1 on 2018-08-06 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import fontawesome_6.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LienReseauSocial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reseau_social', fontawesome_6.fields.IconField(blank=True, max_length=60, verbose_name='réseau social')),
                ('lien', models.URLField()),
                ('ouvrir_nouvel_onglet', models.BooleanField(default=False, help_text="Indique s'il faut ouvrir le lien dans un nouvel onglet")),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'lien réseau social',
                'verbose_name_plural': 'liens réseaux sociaux',
            },
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='media/avatars/')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('lien', models.CharField(blank=True, help_text="Nom de la vue Django vers la page d'accueil du projet", max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/projet/')),
                ('actif', models.BooleanField(default=True)),
            ],
        ),
    ]
