# Generated by Django 2.1b1 on 2018-07-17 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20180717_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='projet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/projet/'),
        ),
    ]
