# Generated by Django 2.1b1 on 2018-07-19 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20180717_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='LienReseauSocial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reseau_social', models.CharField(help_text="Nom de l'icône fontawesome à utiliser.", max_length=50, verbose_name='réseau social')),
                ('lien', models.URLField()),
                ('actif', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='projet',
            name='lien',
            field=models.CharField(blank=True, help_text="Nom de la vue Django vers la page d'accueil du projet", max_length=100, null=True),
        ),
    ]
