# Generated by Django 2.1.2 on 2018-12-24 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20181024_1842'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
