# Generated by Django 2.2.2 on 2019-07-31 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_delete_testmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='date anniversaire'),
        ),
    ]
