# Generated by Django 2.1b1 on 2018-07-19 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20180719_1044'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lienreseausocial',
            options={'verbose_name': 'lien réseau social', 'verbose_name_plural': 'liens réseaux sociaux'},
        ),
        migrations.AddField(
            model_name='lienreseausocial',
            name='ouvrir_nouvel_onglet',
            field=models.BooleanField(default=False, help_text="Indique s'il faut ouvrir le lien dans un nouvel onglet"),
        ),
    ]
