# Generated by Django 2.1b1 on 2018-07-19 09:52

from django.db import migrations
import fontawesome.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20180719_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lienreseausocial',
            name='reseau_social',
            field=fontawesome.fields.IconField(blank=True, max_length=60, verbose_name='réseau social'),
        ),
    ]
