# Generated by Django 2.1b1 on 2018-07-24 20:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0006_auto_20180719_1152'),
        ('avis', '0008_auto_20180724_2205')
    ]

    state_operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='media/avatars/')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil',
                                              to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'base_profil',
            },
            bases=(models.Model,),
        )
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=state_operations)
    ]
