# Generated by Django 2.2.6 on 2020-01-05 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20191031_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='position',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterModelOptions(
            name='projet',
            options={'ordering': ('position',)},
        ),
        migrations.AddField(
            model_name='projet',
            name='external',
            field=models.BooleanField(default=False,
                                      help_text='Cochez lorsque le lien pointe vers un site externe à benbb96.com.',
                                      verbose_name='externe'),
        ),
    ]
