# Generated by Django 2.2.9 on 2020-05-15 14:25

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0008_projet_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
                ('couleur', colorfield.fields.ColorField(default='#FFFFFF', max_length=18)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.TextField(verbose_name='url photo')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='super_moite_moite.Categorie')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TrackTache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date et heure')),
                ('commentaire', models.CharField(blank=True, help_text='Un texte pour donner une explication sur ce track.', max_length=255)),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Profil')),
                ('tache', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='super_moite_moite.Tache')),
            ],
            options={
                'ordering': ('-datetime',),
            },
        ),
        migrations.CreateModel(
            name='PointTache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.PositiveSmallIntegerField(default=1)),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Profil')),
                ('tache', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='super_moite_moite.Tache')),
            ],
        ),
        migrations.CreateModel(
            name='Logement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('slug', models.SlugField(null=True, unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('habitants', models.ManyToManyField(related_name='logements', to='base.Profil')),
            ],
            options={
                'ordering': ('nom',),
            },
        ),
        migrations.AddField(
            model_name='categorie',
            name='logement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='super_moite_moite.Logement'),
        ),
    ]
