# Generated by Django 2.2.12 on 2020-05-15 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_projet_position'),
        ('super_moite_moite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tache',
            name='photo',
            field=models.TextField(default='placeholder.jpg', verbose_name='url photo'),
        ),
        migrations.AlterUniqueTogether(
            name='pointtache',
            unique_together={('tache', 'profil')},
        ),
    ]
