# Generated by Django 2.2.12 on 2020-05-16 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_moite_moite', '0002_auto_20200515_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logement',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
