# Generated by Django 2.2.12 on 2020-05-17 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('super_moite_moite', '0003_auto_20200516_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='logement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='super_moite_moite.Logement'),
        ),
        migrations.AlterField(
            model_name='pointtache',
            name='profil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_taches', to='base.Profil'),
        ),
        migrations.AlterField(
            model_name='pointtache',
            name='tache',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_profils', to='super_moite_moite.Tache'),
        ),
        migrations.AlterField(
            model_name='tache',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taches', to='super_moite_moite.Categorie'),
        ),
        migrations.AlterField(
            model_name='tracktache',
            name='profil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tache_tracks', to='base.Profil'),
        ),
        migrations.AlterField(
            model_name='tracktache',
            name='tache',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='super_moite_moite.Tache'),
        ),
    ]
