# Generated by Django 2.2.12 on 2020-06-09 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_moite_moite', '0004_auto_20200518_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tache',
            name='photo',
            field=models.TextField(default='placeholder.jpg', help_text="Vous pouvez également renseigner l'URL d'une image sur internet.", verbose_name='url photo'),
        ),
    ]
