# Generated by Django 2.2.12 on 2020-06-14 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_moite_moite', '0005_auto_20200610_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
