# Generated by Django 2.2.12 on 2020-06-15 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_moite_moite', '0006_auto_20200615_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tache',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
