# Generated by Django 5.2.12 on 2026-05-02 21:43

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('super_moite_moite', '0007_auto_20200615_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='couleur',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None),
        ),
    ]
