# Generated by Django 2.1.7 on 2019-04-01 15:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0004_delete_testmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jeu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('slug', models.SlugField(null=True, unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name="date d'ajout")),
                ('image', models.ImageField(blank=True, help_text='Une image/photo pour identifier le jeu', null=True, upload_to='jeux/')),
                ('classement', models.BooleanField(default=False, help_text='Cocher cette case pour activer le mode Classement.')),
                ('createur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.Profil')),
            ],
            options={
                'verbose_name_plural': 'jeux',
            },
        ),
        migrations.CreateModel(
            name='Partie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('jeu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parties', to='versus.Jeu')),
            ],
        ),
        migrations.CreateModel(
            name='PartieJoueur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_classement', models.PositiveSmallIntegerField(verbose_name='score ou classement')),
                ('joueur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Profil')),
                ('partie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='versus.Partie')),
            ],
        ),
        migrations.AddField(
            model_name='partie',
            name='joueurs',
            field=models.ManyToManyField(through='versus.PartieJoueur', to='base.Profil'),
        ),
    ]
