# Generated by Django 2.1.7 on 2019-04-16 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_delete_testmodel'),
        ('versus', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partie',
            options={'ordering': ('-date',)},
        ),
        migrations.AlterUniqueTogether(
            name='partiejoueur',
            unique_together={('partie', 'joueur'), ('partie', 'score_classement')},
        ),
    ]
