# Generated by Django 2.1.7 on 2019-05-26 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_delete_testmodel'),
        ('versus', '0002_auto_20190416_2055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Joueur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('slug', models.SlugField(null=True, unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name="date d'ajout")),
                ('profil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.Profil')),
            ],
        ),
        migrations.AlterField(
            model_name='partie',
            name='joueurs',
            field=models.ManyToManyField(through='versus.PartieJoueur', to='versus.Joueur'),
        ),
        migrations.AlterField(
            model_name='partiejoueur',
            name='joueur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='versus.Joueur'),
        ),
    ]
