# Generated by Django 2.2.9 on 2020-03-18 13:23

from django.db import migrations, models


def keep_type_of_game(apps, schema_editor):
    Jeu = apps.get_model("versus", "Jeu")
    db_alias = schema_editor.connection.alias
    for jeu in Jeu.objects.using(db_alias).all():
        if jeu.classement:
            jeu.type = 3
            jeu.save(update_fields=['type'])


def revert_type_of_game(apps, schema_editor):
    Jeu = apps.get_model("versus", "Jeu")
    db_alias = schema_editor.connection.alias
    for jeu in Jeu.objects.using(db_alias).all():
        if jeu.type == 3:
            jeu.classement = True
            jeu.save(update_fields=['classement'])


class Migration(migrations.Migration):

    dependencies = [
        ('versus', '0005_auto_20190820_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='jeu',
            name='type',
            field=models.PositiveSmallIntegerField(default=1, choices=[(1, 'Score'), (2, 'Score inverse'), (3, 'Classement')],
                                                   help_text='Sélectionner le type de jeu qui déterminera la façon de choisir le gagnant.'),
        ),
        migrations.RunPython(keep_type_of_game, revert_type_of_game),
        migrations.RemoveField(
            model_name='jeu',
            name='classement',
        ),
    ]
