# Generated by Django 2.2.12 on 2020-05-16 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('versus', '0006_auto_20200318_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jeu',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='joueur',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
