# Generated by Django 2.2.13 on 2020-10-22 19:36

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('versus', '0007_auto_20200516_1849'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='joueur',
            options={'ordering': ('nom',)},
        ),
        migrations.AlterField(
            model_name='joueur',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='nom', unique=True),
        ),
    ]
