# Generated by Django 2.1.1 on 2018-09-24 22:15

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion
import fontawesome.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='date et heure')),
                ('commentaire', models.CharField(help_text='Un texte pour donner une explication sur ce track.', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('icone', fontawesome.fields.IconField(blank=True, max_length=60)),
                ('color', colorfield.fields.ColorField(default='#FFFFFF', max_length=18)),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('createur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trackers', to='base.Profil')),
            ],
        ),
        migrations.AddField(
            model_name='track',
            name='tracker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='tracker.Tracker'),
        ),
    ]
