# Generated by Django 2.1.1 on 2018-09-24 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
