# Generated by Django 2.1.1 on 2018-10-10 11:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20180928_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date et heure'),
        ),
    ]
