# Generated by Django 2.1.11 on 2019-08-17 15:21

import adminsortable.fields
import colorfield.fields
from django.db import migrations
import django.db.models.deletion
import fontawesome_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_auto_20190816_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', max_length=18, verbose_name='couleur'),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='createur',
            field=adminsortable.fields.SortableForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trackers', to='base.Profil', verbose_name='créateur'),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='icone',
            field=fontawesome_5.fields.IconField(blank=True, max_length=60, verbose_name='icône'),
        ),
    ]
