# Generated by Django 2.1.11 on 2019-08-17 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_auto_20190817_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracker',
            name='slug',
        ),
    ]
