# Generated by Django 5.2.12 on 2026-05-02 10:55

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_remove_tracker_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='valeur',
            field=models.FloatField(blank=True, null=True, verbose_name='valeur'),
        ),
        migrations.AddField(
            model_name='tracker',
            name='type',
            field=models.CharField(choices=[('evenement', 'Événement'), ('mesure', 'Mesure')], default='evenement', max_length=20, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='couleur'),
        ),
    ]
